### ISSUE TITLE
Suggested edit of biased bulletpoint

### ISSUE THREAD

**Issue by rodsmade** [agavrel/42_CheatSheet#12]
Hi! Would it be possible to make the following section gender-neutral and a tick more serious?

"0x07 [Boys Only] Don't waste time flirting : For some who have been living in the basement of their parents' house for years it is a good opportunity to see what a girl looks like in real life. Nevertheless, you have to under that 1/this is not the right time and place to do so."

I know it is meant as a light-hearted joke nodding at the jaded trope of programmers being mostly male and socially inapt. Sometimes that kind of banter might have unintended consequences, such as reinforcing pre-existing discriminatory tropes, or even naturalising behaviour that might be harmful or disrespectful. I believe this is to be the case because it's targeting males as 'potential harassers', considering that flirting in inappropriate moments or when unsolicited is one form of harassment and distress, while it also poorly assumes that boys are exclusively interested in girls, which reinforces the idea of girls as prey to boys.

My suggested revision of that paragraph is as follows:

"0x07 Don't flirt during the piscine. It is not the appropriate time and place to do so. Having someone's attention in a context of mutual helping is not an invitation to flirt, and might come off as distressing or downright disrespectful. Leave it out."

Thanks for your attention. All the best!

**Comment by agavrel** [comment]
Short answer: [Get Help. ](https://youtu.be/3aS3hJfU6e4)

Longer answer: I did IT to avoid dealing with human/social issues. Humans are like a plague, draining the life-stream energy from out planet. Our planet is slowly dying from man-made global warming,  and humans are now too busy fighting over use of pronouns or criticizing people having a different way of life. Isaac Asimov would be laughing in his grave. 

NB: If that matters so much to you do it the proper git way, with a pull request.

**Comment by rodsmade** [comment]
Yeah I understand how harrowing it is the fact that it's all ending one way or the other.
In the mean time, why not strive to make life more comfortable and dignified for everyone?
I'll be opening the PR thanks for the nod :)
