### ISSUE TITLE
Swindle the norminette part is misleading

### ISSUE THREAD

**Issue by keuhdall** [agavrel/42_CheatSheet#4]
In two of your examples [here](https://github.com/agavrel/42_CheatSheet/blob/master/README.md#swindle-the-norminette-truander-la-norme) you actually do declaration and assignation on the same line, which does not comply with 42 norm if I'm not mistaken (I might be wrong as it's been a while since I've done C, even more longer using 42's norm).

Also, I could suggest you one more (**really**) ugly kludge of mine:
```c
if (true)
{
   func1();
   func2();
}
```
5 lines here
```c
if (true)
   func1();
if (true)
   func2();
```
Only 4 lines here :)

**Comment by agavrel** [comment]
good catch and example added
