### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by Maclain27** [agavrel/42_CheatSheet#7]
**Maclain Makanda** siad:

> hi humans 

> I am in for fix my problem to github serriously
I need to get activation on my account and to done the job.

**Comment by Maclain27** [comment]
It non for telepathic humans

**Comment by Maclain27** [comment]
Let me in

**Comment by Maclain27** [comment]
Activate now

**Comment by agavrel** [comment]
Ok I close this issue, seems more related to you. I don't own github shares, so you might want to contact their customer support. Cheers
